<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
		<PackageReference Include="NUnit" Version="4.5.1" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
		<PackageReference Include="XTI_Core.Extensions" Version="1.10.26-dev260424141958857" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Lib\XTI_Secrets.Fakes\XTI_Secrets.Fakes.csproj" />
	</ItemGroup>

</Project>
